# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    4,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\tWSForward\"?\n\tPackageId\x12\x0e\n\x06seq_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ur_idx\x18\x01 \x01(\x05\x12\x11\n\ttotal_cnt\x18\x02 \x01(\x05\"\x85\x01\n\tTransport\x12&\n\x04type\x18\x03 \x01(\x0e\x32\x18.WSForward.TransportType\x12\x10\n\x08receiver\x18\x05 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12 \n\x02id\x18\x02 \x01(\x0b\x32\x14.WSForward.PackageId\"=\n\x07\x43ontrol\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.WSForward.ControlType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"=\n\nClientInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.WSForward.ClientType\"]\n\x12HelloClientControl\x12#\n\x04info\x18\x02 \x01(\x0b\x32\x15.WSForward.ClientInfo\x12\"\n\x04pkgs\x18\x01 \x03(\x0b\x32\x14.WSForward.PackageId\"`\n\x12HelloServerControl\x12&\n\x07\x63lients\x18\x02 \x03(\x0b\x32\x15.WSForward.ClientInfo\x12\"\n\x04pkgs\x18\x01 \x03(\x0b\x32\x14.WSForward.PackageId\"?\n\x13QueryClientsControl\x12(\n\tconnected\x18\x01 \x03(\x0b\x32\x15.WSForward.ClientInfo\"S\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07headers\x18\x03 \x01(\t\x12\x11\n\x04\x62ody\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x42\x07\n\x05_body\"F\n\x08Response\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x0f\n\x07headers\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c*X\n\rTransportType\x12\x0b\n\x07\x43ONTROL\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\x0e\n\nSUBPACKAGE\x10\x03\x12\x0f\n\x0bSTREAM_DATA\x10\x04*<\n\x0b\x43ontrolType\x12\t\n\x05HELLO\x10\x00\x12\x11\n\rQUERY_CLIENTS\x10\x01\x12\x0f\n\x0bQUIT_SIGNAL\x10\x02*$\n\nClientType\x12\n\n\x06\x43LIENT\x10\x00\x12\n\n\x06REMOTE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSPORTTYPE']._serialized_start=771
  _globals['_TRANSPORTTYPE']._serialized_end=859
  _globals['_CONTROLTYPE']._serialized_start=861
  _globals['_CONTROLTYPE']._serialized_end=921
  _globals['_CLIENTTYPE']._serialized_start=923
  _globals['_CLIENTTYPE']._serialized_end=959
  _globals['_PACKAGEID']._serialized_start=29
  _globals['_PACKAGEID']._serialized_end=92
  _globals['_TRANSPORT']._serialized_start=95
  _globals['_TRANSPORT']._serialized_end=228
  _globals['_CONTROL']._serialized_start=230
  _globals['_CONTROL']._serialized_end=291
  _globals['_CLIENTINFO']._serialized_start=293
  _globals['_CLIENTINFO']._serialized_end=354
  _globals['_HELLOCLIENTCONTROL']._serialized_start=356
  _globals['_HELLOCLIENTCONTROL']._serialized_end=449
  _globals['_HELLOSERVERCONTROL']._serialized_start=451
  _globals['_HELLOSERVERCONTROL']._serialized_end=547
  _globals['_QUERYCLIENTSCONTROL']._serialized_start=549
  _globals['_QUERYCLIENTSCONTROL']._serialized_end=612
  _globals['_REQUEST']._serialized_start=614
  _globals['_REQUEST']._serialized_end=697
  _globals['_RESPONSE']._serialized_start=699
  _globals['_RESPONSE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
